### ISSUE TITLE
[Bug] Items add (unit price)

### ISSUE THREAD

**Issue by zikunz** [AY2021S2-CS2113T-T09-4/tp#177]
I realise that there is now a bug when the user tries to add an item with a valid unit price (e.g., 2.5). A screenshot is attached below.
![Screenshot (6)](https://user-images.githubusercontent.com/75139323/113096516-e6e3ca00-9227-11eb-920a-28a9f923ebb4.png)

**Comment by ongweisheng** [comment]
Because the price required was in integer, will change all to BigDecimal in v2.1

**Comment by zikunz** [comment]
> Because the price required was in integer, will change all to BigDecimal in v2.1

I see. Let me change it to BigDecimal :)
